# Generated by Django 5.0.3 on 2024-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refseq_ids', models.CharField(max_length=100)),
                ('variation_ids', models.CharField(max_length=100)),
                ('meanProb', models.FloatField()),
                ('stdProb', models.FloatField()),
                ('pred_label', models.CharField(max_length=100)),
            ],
        ),
    ]
