# Generated by Django 5.0.3 on 2024-08-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponp3web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSV_files',
        ),
    ]
