# Generated by Django 5.1 on 2024-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponp3web', '0004_auto_20240812_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
