# Generated by Django 2.0.7 on 2024-08-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponp3web', '0005_alter_counter_id_alter_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
