# Generated by Django 4.2.16 on 2024-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponp3web', '0007_auto_20240825_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
