# Generated by Django 5.0.3 on 2024-10-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponp3web', '0008_data_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='comments',
        ),
    ]
