# Generated by Django 5.0.3 on 2024-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponp3web', '0009_remove_data_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='comments',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
