# Generated by Django 5.0.3 on 2024-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponp3web', '0010_data_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genomic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomic_variation', models.CharField(max_length=100)),
                ('refseq_ids', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('variation_ids', models.CharField(blank=True, default=' ', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trancript_variation', models.CharField(max_length=95)),
                ('refseq_ids', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('variation_ids', models.CharField(blank=True, default=' ', max_length=50, null=True)),
            ],
        ),
    ]
